language: node_js
sudo: required
before_script:
- npm install -g bower polymer-cli@next
- polymer install
node_js: '6'
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
script:
- xvfb-run polymer test
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test -s 'default'; fi
dist: trusty
env:
  global:
  - secure: ctm7QR2NJDNgx1wOheC81khUedWFvaufgqKpJ4TwDc50YmzhBdyNiqk+0ZutidFuRYHSy/n8zcRcmNdDvJwJhqBQeF7CeOhTVEk3irZjVmn1P7bLkL1L7fE4oeRkEoMKlrzoZiDCeHL9ZN0nKaDDabgOt9xnXKYDtpyj91kWGle3DKUQZEqXD6EUFjnNppaXh9mmaQ8yZygZIuFfr8XYEJY6B37GsAqSwDBZxulOrTuDu2enhizdCCHtyUE7nUyk1FtzA3fZDQ3hj6AU9yToqcrdxpMXrp4vqiO5jUeseCO38/ZtB9Bj/ZgR5yCoSl/kHKhTvLgV7TEfYIUOeoPq+fO3L5lBHclaWqCQjbD/cZtu/bqCTkE7C02RyRP8iURwo7/Db7CyYHIAHlorEu1fa7tp+y/KYwplht0Gaeu7+whL3Od4jZqQLl7jfZ3qOXiiohnBX04Kw0vRCRD5iaS9wOm08nfNKM9c81JwCs1Lv4sId6aYOssJZA2lxgJt1vQFlEyqQDasJIOEUro8WRK22hsuXx4JX1z0YEA5LTBC6a31M24q//Qv+dzQWtLUvnC68kKlVCW6Zs6shpr/Lohtev5HLLcMaK7WvkR0/j44ShOudVHqTgC2YJkAjEG1i3S4sVY8A+xu3mKO0sB56AtPRenPVI7j2p8mS3cVglAS5B0=
  - secure: r5u97ASD2/KTwYevd8zEjAvCnEsw0WLr6urqop+JYR/Ygl23e7myzzj4M4j4JUmQoUIhi4aB9lkm2RJ9SlQlOzjGB3JtI8qdxp3ekZU+yBdh0faYxSN709ymJVOaO4vmxKDRqJ2bjBUVIFVZuo48+Hn66U9H+tIcmQ8VnPnfEJi3ROPq3QJ9D1DKz11pH25zYNMnejPbtIXfYY5/A5NuffzuuhyN1i8s+ytRDRv1H5lEg0ocGu0q8nwBq/+ir/odM9zi6MHiP9sK0pJ3QeVhuBUm8M9c4qJP1+EdF5oXdXS0YJNHHz7tsZWL+P+FvOzlODwZZLwrEz0i2CX5UccbCdhD8HBymCkLiINBkbmckuZwCfLihOdt1E22q2w2hQ5Girc1GR7YiUJ+bOA9XmkHydlhJIBay1uCriHrNkPRrkQd92U+rzoXo7R90egQNe9i1EYHf8zrnVmwT+sQCBMA6fBqxGCO2mlURSAmMArIam3J07qR3fgS80EpzTRiFdc3M55y7DqsfjN+aHVBqzXUIomn8VVF1m6Y0YyDyob5GTa6UX8w41ee8LJX0LQgZcw2BVM/MPgMd487KIBdqi49H2Dp2yjvl4RYmK8OKYz1a94DHHgZO5EB1cEitZ7wAY0yfskA9Nt8vUvzcQxXEC+p84eElRLhexJFU5HzmMWEC64=
